APPLICATION_PATH = File.expand_path(File.join(File.dirname(__FILE__), "."));
SETTINGS_PATH = "#{APPLICATION_PATH}/config/settings.yaml"

TWITTER_CONSUMER_KEY = 'rZ0QG5q6PF3L63EUPTQ6JA'
TWITTER_CONSUMER_SECRET = '3reHZWholqApo7Sw6MGJEYHhTiXE3vRsMSZz5eX7EoM'
TWITTER_OAUTH_TOKEN = '1061688986-NAi0oMGHFtn9Q0Ns0hSDfLGlw4siMYMOiM8uCyD'
TWITTER_OAUTH_TOKEN_SECRET = '8VM6qUDGev0Z2Etb1EtYBiU884cTQfEqA6Uzd1DM'

require "#{APPLICATION_PATH}/lib/ladder"

run Ladder::Server.new
